Exercise 2 - Just print statements with comments
coverdriver27/learningPythonTheHardway pull request #3
Opened 2022-09-02 07:31 UTC by coverdriver27

Exercise 2,  just print statements with commenting

2022-09-02 18:39 UTC, tony-resendiz submitted a review, later dismissed

2022-09-20 16:54 UTC, defrank requested changes
Please also remove the empty file, `Ex04/ex4.py`

2022-09-20 16:54 UTC, defrank commented on Ex02/ex2.py
> +print ("That prints ^")
Please fix the formatting of calling a `print` as a function.

2022-09-22 17:33 UTC, defrank approved these changes
LGTM

2022-09-22 17:35 UTC, merged