Exercise 3 - Working with Numbers and Math
coverdriver27/learningPythonTheHardway pull request #4
Opened 2022-09-02 07:34 UTC by coverdriver27

Working with Numbers and Math Operations

2022-09-02 18:41 UTC, tony-resendiz submitted a review, later dismissed

2022-09-20 17:00 UTC, defrank requested changes
Please remove the file, `Ex04/ex4.py`, and ensure other PRs do not contain files for exercises that are not part of the PR -- even if the files are empty.

2022-09-22 17:52 UTC, coverdriver27 commented on Ex03/ex3.py
> +print ("Now lets calculate you're annual salary:")
Fixed the grammatical issue.

2022-09-22 18:38 UTC, coverdriver27 commented on Ex03/ex3.py
> +print ("Now lets calculate you're annual salary:")
Fixed the formatting

2022-09-22 18:43 UTC, coverdriver27 commented on Ex03/ex3.py
> +print (3 + 2 < 5 - 7) # returns a true or false
Fixed the Comments

2022-09-22 19:25 UTC, defrank approved these changes
LGTM

2022-09-22 19:26 UTC, merged